# Site settings
title: Idaho Organizing Project
email: idorganizingproject@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Idaho Organizing Project resists Trumpism in Idaho.
baseurl: "Idaho-Organizing-Project" # the subpath of your site, e.g. /blog/
# baseurl: ""
url: "https://idahoorganizingproject.github.io" # the base hostname & protocol for your site

# User setting
owner: Idaho Organizing Project
email: idorganizingproject@gmail.com
facebook_username: Idaho-Organizing-Project-217580462042160/
#facebook_username: Idaho-Dreamers-Andrade-Legal-316943685067816
twitter_username: organize208
github_username: IdahoOrganizingProject
address:
  - line:
  - line:
  # Feel free to add more lines here
telephone:
copyright:

# API settings
google_api_key:
include: ['_pages']

# Build settings
markdown: kramdown