# Site settings
title: Idaho Organizing Project
email: idorganizingproject@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Idaho Organizing Project resists Trumpism in Idaho.
baseurl: "/layouts/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Idaho Organizing Project
email: idorganizingproject@gmail.com
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown